<link href="<?=base_url('assets/reports/fontsapi.css');?>" media="all" rel="stylesheet" type="text/css">
<link href="<?=base_url('assets/reports/bootstrap.min.css');?>" media="all" rel="stylesheet" type="text/css">
<link href="<?=base_url('assets/reports/style.css');?>" media="all" rel="stylesheet" type="text/css">
<style>
th {
  font-weight: bold;
  text-align: left;
  border-bottom: 0.5pt solid black;
  line-height: 12px;
}
td{
   line-height: 12px;
}
.line-height-one{
  line-height: 1px;
}
.line-height-two{
  line-height: 2px;
}
</style>
<div style="height: 20px"></div>
<div class="text-center" style="margin-left: 50px;line-height: 8px;"> <h3>JC Worldwide Franchise Inc.</h3><br>
  1196 Batangas Street, San Isidro, Makati City, Philippines<br>
  63.2.‎8894474 to 76</div>
    <div style="height: 5px"></div>
    <div class=" container-fluid main-content">
      <h1 class="line-height-two">Inventory Consumption Report (By Category)
</h1>
      <p class="line-height-one">Date Range: <?=$get_datefrom?> to <?=$get_dateto?></p>
        <p class="line-height-one">Generated By/Date: / <?=$get_dateto?></p>




   <!--   <h2 class="text-right line-height-one"><?=$get_infosummary->id;?></h2>
       <p class="text-right line-height-two"><?=$get_infosummary->trandate?></p>
        <h5>Collected From</h5>
          <p ><?php echo strtoupper($get_edit_membermain->lname . ", " . $get_edit_membermain->fname . " " . $get_edit_membermain->mname)?></p>
          <p class="line-height-one"><?php echo strtoupper($get_edit_credit->branchname) ?></p> -->
      <div class="col-md-6">
        <div class="col-md-12">
         <div class="well">
            <table class="table table-striped table-hover table-bordered"  cellpadding="0" cellspacing="0" border="0" class="display" width="100%">
               <thead >
                  <tr >
                     <th>ID</th>
                     <th>Description</th>
                     <th>Unit</th>
                     <th>Total</th>
                     <th>Location</th>
                  </tr>
               </thead>
               <tbody>
                <?php    
               $query1      = $this->model_reports->icr_by_category_print($get_searchtype,$get_datefrom,$get_dateto,$get_category,$get_location);   
               $count=1; 
               foreach ($query1->result_array() as &$row) {
            echo
           '<tr>
              <td>' . $count .  '</td>
              <td>'.strtoupper($row["itemname"]).'</td>
              <td>'.$row["description"].'</td>
              <td>'.number_format($row["total"],2,".",",").'</td>
              <td>$asd</td>
           </tr>';  }
            ?>
               </tbody>
            </table>
         </div>
      </div>
  </div>

   
